export const stages = [
    {
        id: 1,
        name: 'Orbital Frontier',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.2,
        colors: {
            top: '#020617',
            mid: '#061029',
            bottom: '#14071f',
        },
        enemySpeed: 1,
        enemyTypes: ['drone'],
        bossName: 'Dread Cruiser',
        modifiers: {
            heavyChance: 0.00,
            sniperChance: 0.00,
            kamikazeChance: 0.00,
            derpChance: 0.00,
            powerupChance: 0.26,
            enemyBulletSpeed: 1.0,
        },
    },
    {
        id: 2,
        name: 'Asteroid Graveyard',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.15,
        colors: {
            top: '#1a0f07',
            mid: '#2a1208',
            bottom: '#120609',
        },
        enemySpeed: 1.12,
        enemyTypes: ['drone', 'heavy'],
        bossName: 'Titan Miner',
        modifiers: {
            heavyChance: 0.22,
            sniperChance: 0.02,
            kamikazeChance: 0.00,
            powerupChance: 0.22,
            enemyBulletSpeed: 1.02,
            asteroidDrift: true,
            asteroidDensity: 0.2,
        },
    },
    {
        id: 3,
        name: 'Cyber Grid',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.25,
        colors: {
            top: '#070b1c',
            mid: '#111827',
            bottom: '#240533',
        },
        enemySpeed: 1.2,
        enemyTypes: ['drone', 'heavy'],
        bossName: 'Neon Overlord',
        modifiers: {
            heavyChance: 0.12,
            sniperChance: 0.04,
            kamikazeChance: 0.03,
            derpChance: 0.08,
            droneSpeedBonus: 1.18,
            powerupChance: 0.20,
            enemyBulletSpeed: 1.05,
        },
    },
    {
        id: 4,
        name: 'Ruined Station',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.2,
        colors: {
            top: '#111827',
            mid: '#1f2937',
            bottom: '#020617',
        },
        enemySpeed: 1.28,
        enemyTypes: ['drone', 'heavy'],
        bossName: 'Station Warden',
        modifiers: {
            heavyChance: 0.18,
            sniperChance: 0.06,
            kamikazeChance: 0.04,
            powerupChance: 0.14,
            enemyBulletSpeed: 1.08,
        },
    },
    {
        id: 5,
        name: 'Nebula Rift',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.18,
        colors: {
            top: '#160f29',
            mid: '#312e81',
            bottom: '#020617',
        },
        enemySpeed: 1.36,
        enemyTypes: ['drone', 'heavy'],
        bossName: 'Mist Serpent',
        modifiers: {
            heavyChance: 0.14,
            sniperChance: 0.05,
            kamikazeChance: 0.04,
            powerupChance: 0.26,
            enemyBulletSpeed: 1.05,
            eliteWave: true,
        },
    },
    {
        id: 6,
        name: 'Alien Hive',
        scrollDirection: 'vertical',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.22,
        colors: {
            top: '#120617',
            mid: '#1f1027',
            bottom: '#020617',
        },
        enemySpeed: 1.15,
        enemyTypes: ['drone', 'heavy', 'kamikaze'],
        bossName: 'Hive Mother',
        modifiers: {
            heavyChance: 0.12,
            sniperChance: 0.03,
            kamikazeChance: 0.16,
            derpChance: 0.06,
            powerupChance: 0.22,
            enemyBulletSpeed: 1.06,
        },
    },
    {
        id: 7,
        name: 'Neon Crossfire',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.25,
        colors: {
            top: '#030712',
            mid: '#172554',
            bottom: '#020617',
        },
        enemySpeed: 1.32,
        enemyTypes: ['drone', 'heavy', 'sniper'],
        bossName: 'Crossfire Array',
        modifiers: {
            heavyChance: 0.14,
            sniperChance: 0.16,
            kamikazeChance: 0.04,
            powerupChance: 0.20,
            enemyBulletSpeed: 1.10,
        },
    },
    {
        id: 8,
        name: 'Meteor Belt',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.18,
        colors: {
            top: '#1c1917',
            mid: '#292524',
            bottom: '#020617',
        },
        enemySpeed: 1.22,
        enemyTypes: ['drone', 'heavy'],
        bossName: 'Meteor Harvester',
        modifiers: {
            heavyChance: 0.16,
            sniperChance: 0.05,
            kamikazeChance: 0.05,
            powerupChance: 0.18,
            enemyBulletSpeed: 1.06,
            asteroidDrift: true,
            asteroidDensity: 0.45,
        },
    },
    {
        id: 9,
        name: 'Suicide Run',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.2,
        colors: {
            top: '#190b0b',
            mid: '#3b0a0a',
            bottom: '#020617',
        },
        enemySpeed: 1.38,
        enemyTypes: ['drone', 'heavy', 'kamikaze'],
        bossName: 'Redline Butcher',
        modifiers: {
            heavyChance: 0.10,
            sniperChance: 0.03,
            kamikazeChance: 0.24,
            drunkChance: 0.08,
            powerupChance: 0.22,
            enemyBulletSpeed: 1.08,
        },
    },
    {
        id: 10,
        name: 'War Core',
        scrollDirection: 'vertical',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.28,
        colors: {
            top: '#020617',
            mid: '#431407',
            bottom: '#111827',
        },
        enemySpeed: 1.45,
        enemyTypes: ['drone', 'heavy', 'sniper', 'kamikaze'],
        bossName: 'War Core Prime',
        modifiers: {
            heavyChance: 0.25,
            sniperChance: 0.12,
            kamikazeChance: 0.10,
            powerupChance: 0.28,
            enemyBulletSpeed: 1.12,
            eliteWave: true,
            miniBoss: true,
        },
    },
    // ===================== LEVEL 11-15 (Richtung dynamisch via getScrollDirection) =====================
    {
        id: 11,
        name: 'Pacific Storm',
        scrollDirection: 'horizontal', // Wird von getScrollDirection() überschrieben
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.2,
        colors: {
            top: '#071a3e',
            mid: '#0c2d5e',
            bottom: '#051530',
        },
        enemySpeed: 1.0,
        enemyTypes: ['drone', 'heavy'],
        bossName: 'Yamato Core',
    },
    {
        id: 12,
        name: 'Island Fortress',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.18,
        colors: {
            top: '#0a2e1a',
            mid: '#14532d',
            bottom: '#051a0e',
        },
        enemySpeed: 1.12,
        enemyTypes: ['drone', 'heavy', 'sniper'],
        bossName: 'Bunker Kaiser',
    },
    {
        id: 13,
        name: 'Dogfight Alley',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.22,
        colors: {
            top: '#2a1208',
            mid: '#7c2d12',
            bottom: '#1a0a04',
        },
        enemySpeed: 1.25,
        enemyTypes: ['drone', 'heavy', 'kamikaze'],
        bossName: 'Ace Phantom',
    },
    {
        id: 14,
        name: 'Carrier Assault',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity02',
        bgImageAlpha: 0.2,
        colors: {
            top: '#1a0a2e',
            mid: '#3b0764',
            bottom: '#0a0418',
        },
        enemySpeed: 1.4,
        enemyTypes: ['drone', 'heavy', 'flanker'],
        bossName: 'Leviathan',
    },
    {
        id: 15,
        name: 'Final Intercept',
        scrollDirection: 'horizontal',
        backgroundImage: 'bgCity01',
        bgImageAlpha: 0.25,
        colors: {
            top: '#2e0a0a',
            mid: '#7f1d1d',
            bottom: '#180404',
        },
        enemySpeed: 1.6,
        enemyTypes: ['drone', 'heavy', 'kamikaze', 'sniper'],
        bossName: 'Project 1945',
    },
];

/** Scroll-Richtung basierend auf Level-Nummer: alle 5 Level wechselnd */
export function getScrollDirection(level) {
    const blockIndex = Math.floor((level - 1) / 5);
    return blockIndex % 2 === 0 ? 'horizontal' : 'vertical';
}

export function getStage(index) {
    const base = stages[index % stages.length];
    const cycle = Math.floor(index / stages.length); // 0 for first 15, 1 for 16-30, etc.
    const level = index + 1;

    // Progressive difficulty: each cycle makes enemies faster and tougher
    const speedBonus = cycle * 0.3;
    const hpBonus = cycle * 2;

    // Scroll-Richtung alle 5 Level wechseln
    const scrollDirection = getScrollDirection(level);

    return {
        ...base,
        id: level,
        level: level,
        name: cycle > 0 ? base.name + ' +' + (cycle + 1) : base.name,
        scrollDirection,
        enemySpeed: base.enemySpeed + speedBonus,
        enemyHpBonus: hpBonus,
        bossHpBonus: cycle * 80,
    };
}
